<article class="module width_full">
    <header><h3><?php echo $this->translate('Edit type') ?></h3></header>
    <div class="module_content">
        <?php

        // Retrieving all the messages so we have what to show
        $messages = $form->getMessages();

        // We want to render the errors manually
        $this->formRow()->setRenderErrors(false);

        // Retrieving the forms/fieldsets
        $type = $form->get('type');

        // Retrieving the form elements
        $typeName = $type->get('name');

        /** @var $form \Devices\Form\DevicesFrom */
        $form->setAttribute('action', $this->url('devices/module', array('action' => 'process'), true))->prepare();

        // Messages
        echo $this->partial('partials/form_generic_message.phtml',
            array(
                'success' => $this->success,
                'messages' => $messages,
                'successMessage' => $this->translate('The type info was changed'),
            ));

        // Rendering the form
        echo $this->form()->openTag($form);

        echo $this->showInputError($typeName) . $this->formRow($typeName);

        echo $this->formHidden($type->get('id'));
        echo $this->formHidden($form->get('csrf'));
        echo $this->formElement($form->get('submit'));

        echo $this->form()->closeTag();
        ?>
        <div class="clear"></div>
    </div>
</article>