<article class="module width_full">
    <header><h3><?php echo $this->translate('Add new device') ?></h3></header>
    <div class="module_content">
        <?php

        // Retrieving all the messages so we have what to show
        $messages = $form->getMessages();

        // We want to render the errors manually
        $this->formRow()->setRenderErrors(false);

        // Retrieving the forms/fieldsets
        $device = $form->get('device');
        $device_type = $device->get('type');
        $interface = $device->get('interface');

        // Retrieving the form elements
        $deviceName = $device->get('name');
        $deviceSnmpVersion = $device->get('snmpVersion');
        $deviceSnmpCommunity = $device->get('snmpCommunity');
        $deviceType = $device_type->get('id');

        // Retrieving the form elements
        $interfaceIp = $interface->get('ip');
        $interfaceType = $interface->get('type')->get('id');

        /** @var $form \Devices\Form\DevicesFrom */
        $form->setAttribute(
            'action',
            $this->url('devices/module', array('action' => 'process'), true)
        )->prepare();

        // Messages
        echo $this->partial(
            'partials/form_generic_message.phtml',
            array(
                'success' => $this->success,
                'messages' => $messages,
                'successMessage' => $this->translate('The device was added'),
            )
        );

        // Rendering the form
        echo $this->form()->openTag($form);

        echo $this->showInputError($deviceName) . $this->formRow($deviceName);
        echo $this->showInputError($deviceSnmpVersion) . $this->formRow($deviceSnmpVersion);
        echo $this->showInputError($deviceSnmpCommunity) . $this->formRow($deviceSnmpCommunity);
        echo $this->showInputError($deviceType) . $this->formRow($deviceType);

        //        echo '<fieldset><legend>' . $this->translate('Interface') . '</legend>';
        echo $this->showInputError($interfaceIp) . $this->formRow($interfaceIp);
        echo $this->showInputError($interfaceType) . $this->formRow($interfaceType);
        //        echo '<br/><br/><br/><br/></fieldset>';

        echo $this->formHidden($device->get('id'));
        echo $this->formHidden($form->get('csrf'));
        echo $this->formElement($form->get('submit'));

        echo $this->form()->closeTag();
        ?>
        <div class="clear"></div>
    </div>
</article>