<article class="module width_full">
    <header><h3><?php echo $this->translate('Edit device') ?></h3></header>
    <div class="module_content">
        <?php

        // Retrieving all the messages so we have what to show
        $messages = $form->getMessages();

        // We want to render the errors manually
        $this->formRow()->setRenderErrors(false);

        // Retrieving the forms/fieldsets
        $device = $form->get('device');
        $location = $device->get('location');
        $device_type = $device->get('type');

        // Retrieving the form elements
        $deviceName = $device->get('name');
        $deviceLocation = $location->get('id');
        $deviceType = $device_type->get('id');

        /** @var $form \Devices\Form\DevicesFrom */
        $form->setAttribute('action', $this->url('devices/module', array('action' => 'process'), true))->prepare();

        // Showing the success message
        if ($this->success)
        {
            echo '<h4>' . $this->translate('The device info was changed') . '</h4>';
        }

        // Rendering the form
        echo $this->form()->openTag($form);

        echo $this->showInputError($deviceName) . $this->formRow($deviceName);
        echo $this->showInputError($deviceLocation) . $this->formRow($deviceLocation);
        echo $this->showInputError($deviceType) . $this->formRow($deviceType);

        echo $this->formHidden($device->get('id'));
        echo $this->formHidden($form->get('csrf'));
        echo $this->formElement($form->get('submit'));

        echo $this->form()->closeTag();
        ?>
        <div class="clear"></div>
    </div>
</article>