<article class="module width_full">
    <header>
        <h3>
            <?php echo $this->translate('Information for') . ' "' . $this->device->getName()->get() . '"' ?>
        </h3>
    </header>
    <div class="module_content tableholder">
        <table class="tablesorter" cellspacing="0">
            <thead>
                <tr>
                    <th></th>
                    <th><?php echo $this->translate('Device name') ?></th>
                    <th><?php echo $this->translate('Location') ?></th>
                    <th><?php echo $this->translate('IP') ?></th>
                    <th><?php echo $this->translate('Netmask') ?></th>
                    <th><?php echo $this->translate('MAC') ?></th>
                    <th><?php echo $this->translate('Interface') ?></th>
                    <th><?php echo $this->translate('Bandwidth In') ?></th>
                    <th><?php echo $this->translate('Bandwidth Out') ?></th>
                    <th><?php echo $this->translate('Status') ?></th>
                    <th><?php echo $this->translate('Admin status') ?></th>
                    <th><?php echo $this->translate('Queue length') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php
                echo $this->partial(
                    'devices/index/partials/monitor.phtml',
                    array(
                        'device' => $this->device,
                        'trafficFeature' => $this->trafficFeature,
                    )
                );
                ?>
            </tbody>
        </table>
    </div>
</article>

<article class="module width_full">
    <header>
        <h3>
            <?php echo $this->translate('Interfaces statistics for the last 10 minutes') ?>
        </h3>
    </header>
    <div class="module_content tableholder">
        <table class="tablesorter" cellspacing="0">
            <thead>
                <tr>
                    <th></th>
                    <th><?php echo $this->translate('Interface name') ?></th>
                    <th><?php echo $this->translate('Minimum in') ?></th>
                    <th><?php echo $this->translate('Minimum out') ?></th>
                    <th><?php echo $this->translate('Average in') ?></th>
                    <th><?php echo $this->translate('Average out') ?></th>
                    <th><?php echo $this->translate('Maximum in') ?></th>
                    <th><?php echo $this->translate('Maximum out') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->stats as $interfaceName => $statistic): ?>
                    <tr>
                        <td></td>
                        <td><?php echo $interfaceName ?></td>
                        <td><?php echo $this->bandwidth($statistic['min']->{$interfaceName}->in) ?></td>
                        <td><?php echo $this->bandwidth($statistic['min']->{$interfaceName}->out) ?></td>
                        <td><?php echo $this->bandwidth($statistic['avg']->{$interfaceName}->in) ?></td>
                        <td><?php echo $this->bandwidth($statistic['avg']->{$interfaceName}->out) ?></td>
                        <td><?php echo $this->bandwidth($statistic['max']->{$interfaceName}->in) ?></td>
                        <td><?php echo $this->bandwidth($statistic['max']->{$interfaceName}->out) ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</article>

<article class="module width_full">
    <header>
        <h3>
            <?php echo $this->translate('TCP Connections') ?>
        </h3>
    </header>
    <div class="module_content tableholder">
        <table class="tablesorter" cellspacing="0">
            <thead>
                <tr>
                    <th></th>
                    <th><?php echo $this->translate('Local IP Address') ?></th>
                    <th><?php echo $this->translate('Local Port') ?></th>
                    <th><?php echo $this->translate('Remote IP Address') ?></th>
                    <th><?php echo $this->translate('Remote Port') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php
                echo $this->partial(
                    'devices/index/partials/connections.phtml',
                    array('connections' => $this->device->getTcpConnections())
                );
                ?>
            </tbody>
        </table>
    </div>
</article>