<article class="module width_full">
    <header>
        <h3>
            <?php echo $this->translate('Monitor all devices') ?>
        </h3>
    </header>
    <div class="module_content tableholder">
        <div id="tab1" class="tab_content">
            <table class="tablesorter" cellspacing="0">
                <thead>
                    <tr>
                        <th></th>
                        <th><?php echo $this->translate('Device name') ?></th>
                        <th><?php echo $this->translate('Location') ?></th>
                        <th><?php echo $this->translate('IP') ?></th>
                        <th><?php echo $this->translate('Netmask') ?></th>
                        <th><?php echo $this->translate('MAC') ?></th>
                        <th><?php echo $this->translate('Interface') ?></th>
                        <th><?php echo $this->translate('Bandwidth In') ?></th>
                        <th><?php echo $this->translate('Bandwidth Out') ?></th>
                        <th><?php echo $this->translate('Status') ?></th>
                        <th><?php echo $this->translate('Admin status') ?></th>
                        <th><?php echo $this->translate('Queue length') ?></th>
                    </tr>
                </thead>
                <?php
                echo $this->partialLoop('devices/index/partials/monitor.phtml', $this->devices);
                ?>
            </table>
        </div>
    </div>
</article>