<article class="module width_full">
    <header><h3><?php echo $this->translate('Edit interface') ?></h3></header>
    <div class="module_content">
        <?php

        // Retrieving all the messages so we have what to show
        $messages = $form->getMessages();

        // We want to render the errors manually
        $this->formRow()->setRenderErrors(false);

        // Retrieving the forms/fieldsets
        $interface = $form->get('interface');

        // Retrieving the form elements
        $interfaceDevice = $interface->get('device')->get('id');
        $interfaceName = $interface->get('name');
        $interfaceMac = $interface->get('mac');
        $interfaceIp = $interface->get('ip');
        $interfaceType = $interface->get('type')->get('id');

        /** @var $form \Devices\Form\DevicesFrom */
        $form->setAttribute('action', $this->url('devices/module', array('action' => 'process'), true))->prepare();

        // Messages
        echo $this->partial(
            'partials/form_generic_message.phtml',
            array(
                 'success'        => $this->success,
                 'messages'       => $messages,
                 'successMessage' => $this->translate('The interface info was changed'),
            )
        );

        // Rendering the form
        echo $this->form()->openTag($form);

        echo $this->showInputError($interfaceDevice) . $this->formRow($interfaceDevice);
        echo $this->showInputError($interfaceName) . $this->formRow($interfaceName);
        echo $this->showInputError($interfaceMac) . $this->formRow($interfaceMac);
        echo $this->showInputError($interfaceIp) . $this->formRow($interfaceIp);
        echo $this->showInputError($interfaceType) . $this->formRow($interfaceType);

        echo $this->formHidden($interface->get('id'));
        echo $this->formHidden($form->get('csrf'));
        echo $this->formElement($form->get('submit'));

        echo $this->form()->closeTag();
        ?>
        <div class="clear"></div>
    </div>
</article>