<?php echo $this->doctype(); ?>
<html>
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Network Analyzer'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <!-- Le meta -->
        <?php echo $this->headMeta()->appendName(
            'viewport',
            'width=device-width, initial-scale=1.0'
        ) ?>

        <!-- Le styles -->
        <?php echo $this->headLink(
                       array(
                           'rel' => 'shortcut icon',
                           'type' => 'image/vnd.microsoft.icon',
                           'href' => $this->basePath() . '/img/favicon.ico'
                       )
                   )
                   ->prependStylesheet($this->basePath() . '/css/ie.css', 'screen', 'lt IE 9')
                   ->prependStylesheet($this->basePath() . '/css/jquery-ui-1.10.2.custom.min.css', 'all')
                   ->prependStylesheet($this->basePath() . '/css/layout.css', 'all')
                   ->prependStylesheet($this->basePath() . '/css/styles.css', 'all')
        ?>

        <!-- Le scripts -->
        <?php echo $this->headScript()
                   ->prependFile($this->basePath() . '/js/hideshow.js')
                   ->prependFile($this->basePath() . '/js/jquery.tablesorter.min.js')
                   ->prependFile($this->basePath() . '/js/jquery.equalHeight.js')
                   ->prependFile($this->basePath() . '/js/jquery-ui-1.10.2.custom.min.js')
                   ->prependFile($this->basePath() . '/js/jquery-1.9.1.min.js')
        ?>
    </head>
    <body>

        <div class="report">
            <?php echo $this->content ?>
        </div>


    </body>
</html>
