<?php

$monitorUrl = $this->url(
    'devices/module',
    array('action' => 'monitor', 'id' => $this->device->getDeviceEntity()->getId()),
    true
);

?>

<?php

$addSnifferUrl = $this->trafficFeature;

foreach ($this->device->getInterfaces() as $interface):

    if ($addSnifferUrl) {
        $snifferUrl = $this->url(
            'sniffer/module',
            array(
                'action' => 'index',
                'device' => $this->device->getDeviceEntity()->getId(),
                'interface' => $interface->getName()->get()
            ),
            true
        );
    }

    $interfaceStatus = array(
        1 => $this->translate('Up'),
        2 => $this->translate('Down'),
        3 => $this->translate('Testing'),
        4 => $this->translate('Unknown'),
        5 => $this->translate('Dormant'),
        6 => $this->translate('Not present'),
        7 => $this->translate('Lower layer down'),
    );

    $bandwidthType = array(
        0 => $this->translate('B/s'),
        1 => $this->translate('KB/s'),
        2 => $this->translate('MB/s'),
        3 => $this->translate('GB/s'),
        4 => $this->translate('MB/s'),
    );

    ?>

    <tr>
        <td></td>
        <td><a href="<?php echo $monitorUrl ?>"><?php echo $this->device->getName() ?></a></td>
        <td><?php echo $this->device->getLocation() ?></td>
        <td><?php echo $interface->getIp() ?></td>
        <td><?php echo $interface->getNetmask() ?></td>
        <td><?php echo $interface->getMac() ?></td>
        <td>
            <?php
            if ($addSnifferUrl) {
                echo '<a href="' . $snifferUrl . '">' . $interface->getName() . '</a>';
            } else {
                echo $interface->getName();
            }
            ?>
        </td>
        <td><?php echo $interface->getBandwidthIn() . ' ' . $bandwidthType[$interface->getBandwidthInType()] ?></td>
        <td><?php echo $interface->getBandwidthOut() . ' ' . $bandwidthType[$interface->getBandwidthOutType()] ?></td>
        <td><?php echo $interfaceStatus[$interface->getStatus()->get()] ?></td>
        <td><?php echo $interfaceStatus[$interface->getAdminStatus()->get()] ?></td>
        <td><?php echo $interface->getQueueLength() ?></td>
    </tr>
<?php endforeach; ?>
