<?php

// Messages
if ($this->success === true) {
    echo '<h4>' . $this->successMessage . '</h4>';
} else if (empty($this->messages) && $this->success === false) {
    $unkownMessage = '';

    if (isset($this->unkownMessage)) {
        $unkownMessage = $this->unkownMessage;
    } else {
        $unkownMessage = $this->translate('An unkown error has occured');
    }

    echo '<h4>' . $this->unkownMessage . '</h4>';
}