<?php

// We must not show the menu without a user role
if (!isset($this->userAuth)) {
    return;
}

$menuOptions = array(
    'ulClass' => 'toggle'
);

/** @var $acl \Zend\Permissions\Acl\Acl */
$acl = $this->acl;

/** @var $menu \Zend\View\Helper\Navigation\Menu */
$menu = $this->nav->menu();
$menu->setAcl($acl)
    ->setRole($this->userAuth->getRole());

// Rendering the menus
$menus = array(
    'devices' => $menu->renderMenu(
        $nav->findOneByLabel('Devices'),
        $menuOptions
    ),
    'users' => $menu->renderMenu($nav->findOneByLabel('Users'), $menuOptions),
    'admin' => $menu->renderMenu($nav->findOneByLabel('Admin'), $menuOptions)
)

?>

<aside id="sidebar" class="column">
    <form class="quick_search">
        <input type="text" value="Quick Search"
               onfocus="if(!this._haschanged){this.value=''};this._haschanged=true;">
    </form>
    <hr/>
    <?php if (!empty($menus['devices'])): ?><h3><?php echo $this->translate('Devices') ?></h3><?php endif; ?>
    <?php echo $menus['devices']; ?>
    <?php if (!empty($menus['users'])): ?><h3><?php echo $this->translate('Users') ?></h3><?php endif; ?>
    <?php echo $menus['users']; ?>
    <?php if (!empty($menus['admin'])): ?><h3><?php echo $this->translate('Admin') ?></h3><?php endif; ?>
    <?php echo $menus['admin']; ?>

    <?php if ($acl->isAllowed($this->userAuth->getRole(), 'admin', 'access')): ?>
        <h3><?php echo $this->translate('Application updater') ?></h3>
        <ul class="toggle">
            <li>
                <a class="icn_options"
                   href="<?php echo $this->url('index/module', array('action' => 'update'), true) ?>">
                    <?php echo $this->translate('Update') ?>
                </a>
            </li>
        </ul>
    <?php endif; ?>
    <footer>
        <hr/>
        <p>
            <strong>
                &copy; 2013 Andrei Dincescu. <?php echo $this->translate(
                    'All rights reserved.'
                ) ?>
            </strong>
        </p>

        <p>Theme by <a href="http://www.medialoot.com">MediaLoot</a></p>
    </footer>
</aside>
<!-- end of sidebar -->