<?php

// We must not show the menu without a user role
if (!isset($this->userAuth)) {
    return;
}

$menuOptions = array(
    'ulClass' => 'toggle'
);

/** @var $acl \Zend\Permissions\Acl\Acl */
$acl = $this->acl;

/** @var $menu \Zend\View\Helper\Navigation\Menu */
$menu = $this->nav->menu();
$menu->setAcl($acl)->setRole($this->userAuth->getRole());

// Rendering the menus
$menus = array(
    'devices' => array(
        'container' => $nav->findOneByLabel('Devices'),
        'title' => $this->translate('Devices'),
    ),
    'reports' => array(
        'container' => $nav->findOneByLabel('Reports'),
        'title' => $this->translate('Reports'),
    ),
    'users' => array(
        'container' => $nav->findOneByLabel('Users'),
        'title' => $this->translate('Users'),
    ),
    'admin' => array(
        'container' => $nav->findOneByLabel('Admin'),
        'title' => $this->translate('Admin'),
    ),
);

foreach ($menus as $name => $menuData) {
    if ($menuData['container'] != null) {
        $menus[$name]['container'] = $menu->renderMenu($menuData['container'], $menuOptions);
    }
}

?>

<aside id="sidebar" class="column">
    <form class="quick_search">
        <input type="text" value="Quick Search"
               onfocus="if(!this._haschanged){this.value=''};this._haschanged=true;">
    </form>
    <hr/>
    <?php
    foreach ($menus as $menuName => $menuData) {
        if (!empty($menuData['container'])) {
            echo '<h3>' . $menuData['title'] . '</h3>';
            echo $menuData['container'];
        }
    }
    ?>
    <footer>
        <hr/>
        <p>
            <strong>
                &copy; 2013 Andrei Dincescu. <?php echo $this->translate(
                    'All rights reserved.'
                ) ?>
            </strong>
        </p>

        <p>Theme by <a href="http://www.medialoot.com">MediaLoot</a></p>
    </footer>
</aside>
<!-- end of sidebar -->