<?php

/** @var $nav Zend\View\Helper\Navigation */
$this->nav = $this->navigation('navigation');
$this->nav->setTranslator(
    $this->getHelperPluginManager()->get('translate')->getTranslator()
);

?>
<?php echo $this->doctype(); ?>
<html>
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Network Analyzer'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <!-- Le meta -->
        <?php echo $this->headMeta()->appendName(
            'viewport',
            'width=device-width, initial-scale=1.0'
        ) ?>

        <!-- Le styles -->
        <?php echo $this->headLink(
                       array(
                           'rel' => 'shortcut icon',
                           'type' => 'image/vnd.microsoft.icon',
                           'href' => $this->basePath() . '/img/favicon.ico'
                       )
                   )
                   ->prependStylesheet($this->basePath() . '/css/ie.css', 'screen', 'lt IE 9')
                   ->prependStylesheet($this->basePath() . '/css/jquery-ui-1.10.2.custom.min.css', 'all')
                   ->prependStylesheet($this->basePath() . '/css/layout.css', 'all')
                   ->prependStylesheet($this->basePath() . '/css/styles.css', 'all')
        ?>

        <!-- Le scripts -->
        <?php echo $this->headScript()
                   ->prependFile($this->basePath() . '/js/hideshow.js')
                   ->prependFile($this->basePath() . '/js/jquery.tablesorter.min.js')
                   ->prependFile($this->basePath() . '/js/jquery.equalHeight.js')
                   ->prependFile($this->basePath() . '/js/jquery-ui-1.10.2.custom.min.js')
                   ->prependFile($this->basePath() . '/js/jquery-1.9.1.min.js')
        ?>

        <script type="text/javascript">
            $(document).ready(function ()
            {
                $(".tablesorter").tablesorter();

                //When page loads...
                $(".tab_content").hide(); //Hide all content
                $("ul.tabs li:first").addClass("active").show(); //Activate first tab
                $(".tab_content:first").show(); //Show first tab content

                //On Click Event
                $("ul.tabs li").click(function ()
                {

                    $("ul.tabs li").removeClass("active"); //Remove any "active" class
                    $(this).addClass("active"); //Add "active" class to selected tab
                    $(".tab_content").hide(); //Hide all tab content

                    //Find the href attribute value to identify the active tab + content
                    var activeTab = $(this).find("a").attr("href");

                    //Fade in the active ID content
                    $(activeTab).fadeIn();

                    return false;
                });

                $('.column').equalHeight();

            });
        </script>
    </head>
    <body>

        <div class="report">
            <?php echo $this->content ?>
        </div>


    </body>
</html>
