<?php

/** @var $nav Zend\View\Helper\Navigation */
$this->nav = $this->navigation('navigation');
$this->nav->setTranslator($this->getHelperPluginManager()->get('translate')->getTranslator());

?>
<?php echo $this->doctype(); ?>
<html>
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Network Analyzer'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <!-- Le meta -->
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(
            array(
                'rel'  => 'shortcut icon',
                'type' => 'image/vnd.microsoft.icon',
                'href' => $this->basePath() . '/img/favicon.ico'
            )
        )->prependStylesheet($this->basePath() . '/css/ie.css', 'screen', 'lt IE 9')
            ->prependStylesheet($this->basePath() . '/css/jquery-ui-1.10.2.custom.min.css')
            ->prependStylesheet($this->basePath() . '/css/layout.css')
            ->prependStylesheet($this->basePath() . '/css/styles.css')
        ?>

        <!-- Le scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/hideshow.js')
            ->prependFile($this->basePath() . '/js/jquery.tablesorter.min.js')
            ->prependFile($this->basePath() . '/js/jquery.equalHeight.js')
            ->prependFile($this->basePath() . '/js/jquery-ui-1.10.2.custom.min.js')
            ->prependFile($this->basePath() . '/js/jquery-1.9.1.min.js')
        ?>

        <script type="text/javascript">
            $(document).ready(function ()
            {
                $(".tablesorter").tablesorter();

                //When page loads...
                $(".tab_content").hide(); //Hide all content
                $("ul.tabs li:first").addClass("active").show(); //Activate first tab
                $(".tab_content:first").show(); //Show first tab content

                //On Click Event
                $("ul.tabs li").click(function ()
                {

                    $("ul.tabs li").removeClass("active"); //Remove any "active" class
                    $(this).addClass("active"); //Add "active" class to selected tab
                    $(".tab_content").hide(); //Hide all tab content

                    //Find the href attribute value to identify the active tab + content
                    var activeTab = $(this).find("a").attr("href");

                    //Fade in the active ID content
                    $(activeTab).fadeIn();

                    return false;
                });

                $('.column').equalHeight();

            });
        </script>
    </head>
    <body>
        <header id="header">
            <hgroup>
                <h1 class="site_title">
                    <a href="<?php echo $this->url('home', array(), true) ?>">
                        <?php echo $this->translate('Network Analyzer') ?>
                    </a>
                </h1>

                <h2 class="section_title"><?php echo $this->translate('Dashboard') ?></h2>
                <?php echo $this->partial('partials/language.phtml', $this->vars()) ?>
            </hgroup>
        </header>
        <!-- end of header bar -->

        <section id="secondary_bar">
            <div class="user"></div>
            <div class="breadcrumbs_container">
                <article class="breadcrumbs">
                    <a href="<?php echo $this->url('index', array(), true) ?>">
                        <?php echo $this->translate('Network Analyzer') ?>
                    </a>

                    <?php echo $this->nav->breadcrumbs()->setMinDepth(0)->setPartial('partials/breadcrumb.phtml'); ?>

                </article>
            </div>
        </section>
        <!-- end of secondary bar -->

        <?php echo $this->partial('partials/side_menu.phtml', $this->vars()) ?>

        <section id="main" class="column">

            <h4 class="alert_info">
                Welcome to the free MediaLoot admin panel template, this could
                be an informative
                message.
            </h4>

            <article class="module width_full">
                <header><h3>Stats</h3></header>
                <div class="module_content">
                    <article class="stats_graph">
                    </article>

                    <article class="stats_overview">
                        <div class="overview_today">
                            <p class="overview_day">Today</p>

                            <p class="overview_count">1,876</p>

                            <p class="overview_type">Hits</p>

                            <p class="overview_count">2,103</p>

                            <p class="overview_type">Views</p>
                        </div>
                        <div class="overview_previous">
                            <p class="overview_day">Yesterday</p>

                            <p class="overview_count">1,646</p>

                            <p class="overview_type">Hits</p>

                            <p class="overview_count">2,054</p>

                            <p class="overview_type">Views</p>
                        </div>
                    </article>
                    <div class="clear"></div>
                </div>
            </article>
            <!-- end of stats article -->

            <?php echo $this->content ?>

            <div class="spacer"></div>
        </section>

    </body>
</html>
