<article class="module width_full">
    <header><h3><?php echo $this->translate('Edit user') ?></h3></header>
    <div class="module_content">
        <?php

        // Retrieving all the messages so we have what to show
        $messages = $form->getMessages();

        // We want to render the errors manually
        $this->formRow()->setRenderErrors(false);

        // Retrieving the forms/fieldsets
        $user = $form->get('user');
        $role = $user->get('role');

        // Retrieving the form elements
        $userName = $user->get('name');
        $userEmail = $user->get('email');
        $userRole = $role->get('id');

        /** @var $form \Library\Form\AbstractFrom */
        $form->setAttribute('action', $this->url('users/module', array('action' => 'process'), true))->prepare();

        // Messages
        echo $this->partial('partials/form_generic_message.phtml',
            array(
                'success' => $this->success,
                'messages' => $messages,
                'successMessage' => $this->translate('The user info was updated'),
            ));

        // Rendering the form
        echo $this->form()->openTag($form);

        echo $this->showInputError($userName) . $this->formRow($userName);
        echo $this->showInputError($userEmail) . $this->formRow($userEmail);
        echo $this->showInputError($userRole) . $this->formRow($userRole);

        echo $this->formHidden($user->get('id'));
        echo $this->formHidden($form->get('csrf'));
        echo $this->formElement($form->get('submit'));

        echo $this->form()->closeTag();
        ?>
        <div class="clear"></div>
    </div>
</article>