<article class="module width_full">
    <header>
        <h3>
            <?php echo $this->translate('Devices traffic') . ' ' . $this->deviceInfo->name; ?>
        </h3>
    </header>
    <div class="module_content tableholder">
        <table class="tablesorter" cellspacing="0">
            <thead>
                <tr>
                    <th></th>
                    <th><?php echo $this->translate('Date') ?></th>
                    <th><?php echo $this->translate('Time') ?></th>
                    <th><?php echo $this->translate('Source socket') ?></th>
                    <th><?php echo $this->translate('Destination socket') ?></th>
                    <th><?php echo $this->translate('Interface') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->reportData as $data): ?>
                    <tr>
                        <td></td>
                        <td><?php echo $data['date'] ?></td>
                        <td><?php echo date('H:i:s', $data['time']) ?></td>
                        <td><?php echo $data['src_ip'] . ' : ' . $data['src_port'] ?></td>
                        <td><?php echo $data['dst_ip'] . ' : ' . $data['dst_port'] ?></td>
                        <td><?php echo $data['iface_name'] ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</article>
