<article class="module width_full">
    <header><h3><?php echo $this->translate('Devices traffic') ?></h3></header>
    <div class="module_content">
        <?php

        // Retrieving all the messages so we have what to show
        $messages = $form->getMessages();

        // We want to render the errors manually
        $this->formRow()->setRenderErrors(false);

        $report = $form->get('devices_traffic');

        $devicesNames = $report->get('device')->get('id');
        $trafficType = $report->get('traffic_type');
        $days = $report->get('days');

        /** @var $form \Reports\Form\DevicesTraffic */
        $form->setAttribute(
            'action',
            $this->url('reports/module', array('action' => 'generate', 'dispatch' => 'devicesTraffic'), true)
        )->prepare();

        // Messages
        echo $this->partial(
            'partials/form_generic_message.phtml',
            array(
                'success' => $this->success,
                'messages' => $messages,
                'successMessage' => '',
            )
        );

        // Rendering the form
        echo $this->form()->openTag($form);

        echo $this->showInputError($devicesNames) . $this->formRow($devicesNames);
        echo $this->showInputError($trafficType) . $this->formRow($trafficType);
        echo $this->showInputError($days) . $this->formRow($days);
        ?>

        <?php
        echo $this->formHidden($form->get('csrf'));
        echo $this->formElement($form->get('submit'));

        echo $this->form()->closeTag();

        ?>
        <div class="clear"></div>
    </div>
</article>
