<article class="module width_full">
    <header><h3><?php echo $this->translate('Interface traffic report') ?></h3></header>
    <div class="module_content">
        <?php

        $report = $form->get('interface_traffic');

        $devicesNames = $report->get('id');

        /** @var $form \Reports\Form\InterfaceTraffic */
        $form->setAttribute(
            'action',
            $this->url('reports/module', array('action' => 'generate'), true)
        )->prepare();

        // Rendering the form
        echo $this->form()->openTag($form);

        echo $this->showInputError($devicesNames) . $this->formRow($devicesNames);
        ?>

        <?php
        echo $this->formHidden($form->get('csrf'));
        echo $this->formElement($form->get('submit'));

        echo $this->form()->closeTag();

        ?>
        <div class="clear"></div>
    </div>
</article>