<?php

$monitorUrl = $this->url('devices/module', array('action' => 'monitor', 'id' => $this->id), true);
$editUrl = $this->url('devices/module', array('action' => 'editForm', 'id' => $this->id), true);
$deleteUrl = $this->url('devices/module', array('action' => 'delete', 'id' => $this->id), true);

?>

<tr>
    <td><input type="checkbox"></td>
    <td><?php echo $this->name ?></td>
    <td><?php echo $this->typeName ?></td>
    <td><?php echo $this->locationName ?></td>
    <td>
        <a href="<?php echo $monitorUrl ?>">
            <input type="image" src="<?php $this->mediaSource('images', 'monitor.png') ?>"
                   title="<?php echo $this->translate('Monitor') ?>">
        </a>
        <a href="<?php echo $editUrl ?>">
            <input type="image" src="<?php $this->mediaSource('images', 'icn_edit.png') ?>"
                   title="<?php echo $this->translate('Edit') ?>">
        </a>
        <a href="<?php echo $deleteUrl ?>">
            <input type="image" src="<?php $this->mediaSource('images', 'icn_trash.png') ?>"
                   title="<?php echo $this->translate('Trash') ?>">
        </a>
    </td>
</tr>